name: Deploy to Fly.io

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency: deploy-api
    steps:
      - uses: actions/checkout@v4
      - name: Install flyctl
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 2
          max_attempts: 3
          retry_wait_seconds: 10
          command: |
            curl -L https://fly.io/install.sh | FLYCTL_INSTALL=/usr/local sh
      - run: flyctl deploy --config fly.prod-api.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-web:
    name: Deploy Web
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency: deploy-web
    steps:
      - uses: actions/checkout@v4
      - name: Install flyctl
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 2
          max_attempts: 3
          retry_wait_seconds: 10
          command: |
            curl -L https://fly.io/install.sh | FLYCTL_INSTALL=/usr/local sh
      - run: flyctl deploy --config fly.prod-web.toml --remote-only --build-arg "NEXT_PUBLIC_POSTHOG_KEY=$POSTHOG_KEY" --build-arg "NEXT_PUBLIC_POSTHOG_HOST=https://eu.i.posthog.com"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
